AllCops:
  Exclude:
    - 'db/schema.rb'
Style/Documentation:
  Enabled: false
Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Bundler/OrderedGems:
  Enabled: false
